Feature/user ask question
Melchakovartem/thinknetica-project pull request #1
Opened 2017-05-17 15:48 UTC by Melchakovartem

Созданы модели Question и Answer, покрытые тестами.

2017-05-18 09:11 UTC, vkurennov requested changes
Исправь замечания, залей в эту же ветку и снова сдай на проверку в системе обучения. Новый пулл реквест делать НЕ нужно!

2017-05-18 09:11 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  it "validates answer belongs to question" do
Это старнный тест. По описанию вроде бы валидацию тестируешь, а по факту- ассоциацию. Но в shoulda-matchers есть тесты для ассоциаций, используй их

2017-05-18 09:11 UTC, vkurennov commented on spec/models/question_spec.rb
> +RSpec.describe Question, type: :model do
А где тесты для ассоциаций?

2017-05-18 09:54 UTC, palkan-th requested changes

2017-05-18 09:54 UTC, palkan-th commented on db/migrate/20170517145255_create_answers.rb
> +      t.integer :question_id
Здесь нам не помешал бы индекс и ограничение на внешний ключ. В рельсах это можно сделать проще, если использовать вместо типа метод `reference` или даже `belongs_to`:

```ruby
create_table :answers do |t|
  t.belongs_to :question, index: true, foreign_key: true
end
```

2017-05-18 09:54 UTC, palkan-th commented on db/migrate/20170517145255_create_answers.rb
> +      t.string :body
В чём отличие `t.string` и `t.text`? И какой же всё-таки тип нам нужен?

2017-05-18 09:54 UTC, palkan-th commented on spec/models/question_spec.rb
> +  it { should have_many(:answers) }
`dependent`?

2017-05-18 12:11 UTC, palkan-th commented on spec/models/question_spec.rb
> +  it { should have_many(:answers) }
???

2017-05-19 10:14 UTC, Melchakovartem commented on db/migrate/20170517145255_create_answers.rb
> +      t.string :body
string - используется, для полей с малой длиной текста.
text - с произвольной длиной текста.
Исправлю.

2017-05-21 17:57 UTC, merged